[build]
  command = "npm run build"
  publish = ".next"

[context.staging]
  command = "npm run build"
  [context.staging.environment]
    NEXT_PUBLIC_IS_STAGING = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
